
TRAIN_ROOT_DIR = '/home/ubuntu/Duluth/train_set'
TEST_ROOT_DIR = '/home/ubuntu/Duluth/test_set'



BATCH_SIZE = 8
NUM_EPOCHS = 110
GR_PRE_TRAINING_EPOCHS = 80
GR_LEARNING_RATE = 6e-5
DR_LEARNING_RATE = 5e-5
EMBEDDING_LOSS_TYPE = 'cosine'
ENABLE_AUG = True
SAVE_DISCRIMINATOR_WEIGHTS = True